# Generated by Django 3.1 on 2025-06-11 10:25

from django.db import migrations, models
import streams.models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('unique_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('feedback_text', models.TextField()),
                ('video_url', models.URLField()),
                ('trimmed_video', models.FileField(upload_to=streams.models.upload_to)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
